### ISSUE TITLE
[BE-4] Refactor with pep8 standars

### ISSUE THREAD

**Issue by AnilKOC** [Ridvansezen/Django-Blog-Project#11]
Project has some defination names problems. 
We need to fix with standarts of pep8

https://peps.python.org/pep-0008/

@Ridvansezen

**Comment by Ridvansezen** [comment]
BE-4: Class and Function names updated according to pep8 standards.

**Comment by Ridvansezen** [comment]
BE-4: Lines have been updated with a maximum character limit of 79, Comment lines have been added.

@AnilKOC
