### ISSUE TITLE
[BE-5] Need to remove __pycache__ files.

### ISSUE THREAD

**Issue by AnilKOC** [Ridvansezen/Django-Blog-Project#14]
Need to remove __pycache__ files.
And we should add the roots to the .gitignore
@Ridvansezen

**Comment by Ridvansezen** [comment]
__pycache__ files removed and added the roots to the .gitignore file.

**Comment by Ridvansezen** [comment]
pycache files removed and added the roots to the .gitignore file.

@AnilKOC

**Comment by AnilKOC** [comment]
@Ridvansezen There are still have a issues.

**Comment by Ridvansezen** [comment]
pycache files roots added to the gitignore.

@AnilKOC
